version: "3.7"

services:
  my-retail:
    build: .
    container_name: retail_api
    restart: on-failure
    environment:
      SPRING_APPLICATION_NAME: docker-retail
      database_name: admin
      database_username: admin
      database_password: admin
      database_host: 192.168.86.181
      database_port: 27017
    depends_on:
      - redis
      - jaeger
    links:
      - redis
      - jaeger
    ports:
      - '8097:8097'
    networks:
      - gateway
  mongo:
    image: mongo:latest
    container_name: mongo_retail
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - /Volumes/AtulMac/Github/myretail-mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - gateway
  redis:
    image: 'bitnami/redis:5.0'
    container_name: redis_retail
    restart: always
    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL
      REDIS_PASSWORD: 9@3rcvsOTcss
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - gateway
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger_retail
    restart: always
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
    networks:
      - gateway
networks:
  gateway: {}
volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local