server:
  port: ${port:8097}
spring:
  data:
    mongodb:
      database: ${database_name:myRetail}
      username: ${database_username:myRetail}
      password: ${database_password:myRetail}
      host: ${database_host:localhost}
      port: ${database_port:27017}
  redis:
    host: localhost
    port: 6379
  zipkin:
    base-url: htpp://localhost:9411/
  sleuth:
    sampler:
      probability: 1
#  security:
#    user:
#      name: admin
management:
  endpoint:
    health:
      enabled: true
#      password: admin